/*VERB*/
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('walk', 'walks', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('talk', 'talks', 0, 3);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('live', 'lives', 0, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('try', 'tries', 0, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('make', 'makes', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('come', 'comes', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('practice', 'practices', 0, 3);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('love', 'loves', 0, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('impress', 'impresses', 0, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('get', 'gets', 0, 2);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('belong', 'belongs', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('sing', 'sings', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('serve', 'serves', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('appreciate', 'appreciates', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('honor', 'honors', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('bring', 'brings', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('create', 'creates', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('recognise', 'recognises', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('bow', 'bows', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('fill', 'fills', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('guide', 'guides', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('empty', 'empties', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('share', 'shares', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('speak', 'speaks', 0, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('think', 'thinks', 0, 0);
/*ADJECTIVE*/
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('happy', 'happily', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('beautiful', 'beautifully', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('bountiful', 'bountifully', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('blissful', 'blissfully', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('compassionate', 'compassionately', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('high', 'highly', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('proud', 'proudly', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('calm', 'calmly', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('everlasting', 'everlastingly', 1, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('infinite', 'infinitely', 1, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('elevated', 'elevatedly', 1, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('straight', 'straightly', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('simple', 'simply', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('ultimate', 'ultimately', 1, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('serious', 'seriously', 1, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('honest', 'honestly', 1, 0);
/*CONCEPT*/
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('compassion', 'compassion', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('love', 'love', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('prosperity', 'prosperity', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('peace of mind', 'peace of mind', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('kindness', 'kindness', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('gratitude', 'gratitude', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('forgiveness', 'forgiveness', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('happiness', 'happiness', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('contentment', 'contentment', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('strength', 'strength', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('knowledge', 'knowledge', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('wisdom', 'wisdom', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('faith', 'faith', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('joy', 'joy', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('essence', 'essence', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('success', 'success', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('soul', 'the soul', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('self', 'the self', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('power', 'the power', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('intuition', 'intuition', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('greatness', 'greatness', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('happiness', 'happiness', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('life', 'the life', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('experience', 'experience', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('beauty', 'beauty', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('fear', 'fear', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('vengeance', 'vengeance', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('peace', 'peace', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('tranquility', 'tranquility', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('harmony', 'harmony', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('understanding', 'understanding', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('truth', 'the truth', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('grace', 'the grace', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('bliss', 'bliss', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('infinity', 'infinity', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('trust', 'trust', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('participation', 'participation', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('reality', 'reality', 2, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('universe', 'the universe', 2, 0);
/*OBJECT*/
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('person', 'people', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('fountain', 'fountains', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('heart', 'hearts', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('question', 'questions', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('thing', 'things', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('limit', 'limits', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('action', 'actions', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('merit', 'merits', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('piece', 'pieces', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('infinity', 'infinities', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('enemy', 'enemies', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('friend', 'friends', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('gift', 'gifts', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('experience', 'experiences', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('soul', 'souls', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('achievement', 'achievements', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('day', 'days', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('source', 'sources', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('victory', 'victories', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('opportunity', 'opportunities', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('power', 'powers', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('ship', 'ships', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('sail', 'sails', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('river', 'rivers', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('water', 'waters', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('art', 'arts', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('head', 'heads', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('flow', 'flows', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('anchor', 'anchors', 3, 1);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('chance', 'chances', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('reality', 'realities', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('voice', 'voices', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('smile', 'smiles', 3, 0);
INSERT INTO Expression (field_1, field_2, type, flags) VALUES ('law', 'laws', 3, 0);
/*Format_String*/
INSERT INTO Format_String (str, data, count) VALUES ('People who %s are %s.', X'200'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Walk %s, talk %s, live %s.', X'30303'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s is the %s of %s.', X'60604'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('Never %s to %s others, %s to %s yourself.', X'68006800'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('%s is within us.', X'4'::bigint, 1);
INSERT INTO Format_String (str, data, count) VALUES ('%s is an experience of %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Give %s, get %s.', X'704'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Give %s, get %s.', X'C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s will make you %s.', X'204'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s comes %s by %s.', X'60604'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s has no %s. %s has no %s.', X'3C142C04'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('An attitude of %s brings %s.', X'2704'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Practice %s, %s and %s.', X'342C04'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s comes from %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s comes from %s.', X'704'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s come from %s.', X'507'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Your %s is your own %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Have %s in your %s and %s in your %s.', X'2F2C2704'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('%s is the %s of %s.', X'342C04'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('I am %s, I am %s, I am %s.', X'322A02'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('Let %s come to you.', X'7'::bigint, 1);
INSERT INTO Format_String (str, data, count) VALUES ('Let %s come to you.', X'4'::bigint, 1);
INSERT INTO Format_String (str, data, count) VALUES ('Where there is %s, there are no %s.', X'704'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Where there is %s, there is no %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Let your %s speak to others'' %s.', X'2706'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s is the highest %s.', X'2C04'::bigint, 2);
/*NEW*/
INSERT INTO Format_String (str, data, count) VALUES ('Your %s is not what you %s, it''s what you %s.', X'280004'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('Your %s is your best friend.', X'4'::bigint, 1);
INSERT INTO Format_String (str, data, count) VALUES ('%s from your %s.', X'600'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('The art of %s is to %s all.', X'6004'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s is a %s. %s is the %s.', X'2D2EA604'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('There is no %s without %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s has no %s and no %s.', X'342C04'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s yourself and %s your %s.', X'60800'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('To be %s is the highest %s of %s.', X'50602'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('May this %s bring you %s, %s and %s.', X'352C0406'::bigint, 4);

INSERT INTO Format_String (str, data, count) VALUES ('%s is %s.', X'204'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s creates %s.', X'D04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s brings %s and %s.', X'342C04'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s is a %s of %s and %s.', X'342CA605'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('%s is a %s %s.', X'6A204'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('Your greatest %s is %s.', X'2D04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s without %s is a %s without %s.', X'2FA62C04'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('%s is the greatest %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s that you are %s.', X'500'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Our %s %s and our %s is %s with %s and %s.', X'2C04022E0106'::bigint, 6);
INSERT INTO Format_String (str, data, count) VALUES ('Let your %s guide you.', X'6'::bigint, 1);
INSERT INTO Format_String (str, data, count) VALUES ('You will always live %s if you live with your %s.', X'602'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s is the %s of %s; your %s is requested.', X'342C2604'::bigint, 4);
INSERT INTO Format_String (str, data, count) VALUES ('%s will give you %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s, %s and %s are the %s of %s.', X'3C07342C04'::bigint, 5);
INSERT INTO Format_String (str, data, count) VALUES ('Life is a %s. Love is %s. Grace is %s.', X'2D05A6'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s yourself and let %s fill you.', X'500'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s to %s.', X'800'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('The %s of your %s is %s.', X'2C0406'::bigint, 3);
INSERT INTO Format_String (str, data, count) VALUES ('%s is %s.', X'204'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s %s.', X'500'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('%s is in your %s.', X'2C04'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('You don''t need %s, you are the %s.', X'404'::bigint, 2);
INSERT INTO Format_String (str, data, count) VALUES ('Think %s and think %s.', X'2B03'::bigint, 2);
